spring:
  datasource:
    url: jdbc:mysql://15.164.165.70:3306/hackathon_db?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false